#!/bin/bash -e

# Environment Setup Script for PHP Cognitive Complexity Dev Container
#
# This script generates a .env file with environment variables needed for development.
#
# IMPORTANT: This script MUST be run on the WSL2 host BEFORE starting the Dev Container,
# because it needs to detect the WSL2 IP address for XDebug configuration.
#
# Usage:
#   1. Clone the repository in WSL2
#   2. Run this script: .docker/generate-env.sh
#   3. Start the Dev Container in VS Code

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

echo "🔧 Generating .env file for Dev Container..."
echo "📁 Working from project root: $(pwd)"

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
    echo "📝 Removing existing .env file..."
    rm -f "$ENV_FILE"
fi

echo "🔍 Detecting WSL2 IP address..."
WSL_IP=$(ip route | grep default | awk '{print $3}')

if [ -z "$WSL_IP" ]; then
    echo "❌ Error: Could not detect WSL2 IP address"
    echo "   This script must be run inside WSL2 environment"
    exit 1
fi

if ! echo "$WSL_IP" | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$' > /dev/null; then
    echo "❌ Error: Invalid IP address format: $WSL_IP"
    exit 1
fi

echo "✅ Detected WSL2 IP: $WSL_IP"

echo "📝 Writing environment variables to $ENV_FILE..."

cat > "$ENV_FILE" << EOF
# Environment variables for PHP Cognitive Complexity Dev Container
# Generated automatically by .docker/generate-env.sh
# Do not edit this file manually - it will be overwritten

# Application configuration
APP_NAME=ncac-php-cognitive-complexity
PHP_VERSION=8.2.30
APP_ROOT=/workspace

# WSL2 and XDebug configuration
WSL_IP=$WSL_IP
XDEBUG_PORT=9048

# Generation timestamp
GENERATED_AT=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
EOF

echo "✅ Environment file generated successfully!"
echo ""
echo "📋 Generated variables:"
echo "   APP_NAME: ncac-php-cognitive-complexity"
echo "   PHP_VERSION: 8.2.30"
echo "   APP_ROOT: /workspace"
echo "   WSL_IP: $WSL_IP"
echo "   XDEBUG_PORT: 9048"
echo ""
echo "🚀 You can now start the Dev Container in VS Code"
